# Generated by Django 2.1.1 on 2018-10-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='media/profile_image/779d213e8b3d36e45f97e23a9eafb478.png', upload_to='media/profile_image'),
        ),
    ]
