# Generated by Django 2.1.1 on 2018-10-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_thread_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ManyToManyField(to='app.Tag')),
            ],
        ),
    ]
