# Generated by Django 2.1.1 on 2018-10-21 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0018_followtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='followtag',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followtag',
            name='tag',
            field=models.ManyToManyField(related_name='tag_set', to='app.Tag'),
        ),
    ]
