# Generated by Django 2.1.2 on 2018-10-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20181021_1107'),
        ('app', '0020_auto_20181022_1728'),
    ]

    operations = [
    ]
