# Generated by Django 2.1.1 on 2018-10-24 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_comment_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentfile',
            name='commentId',
        ),
        migrations.RemoveField(
            model_name='commentfile',
            name='fileId',
        ),
        migrations.DeleteModel(
            name='CommentFile',
        ),
    ]
