# Generated by Django 2.1.1 on 2018-10-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20181025_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followtag',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='tag_set', to='app.Tag'),
        ),
    ]
