# Generated by Django 2.1.1 on 2018-10-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followtag',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='tag_set', to='app.Tag'),
        ),
    ]
